name: indoor_nav
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.3.0
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blosc=1.21.1
  - bzip2=1.0.8
  - c-blosc2=2.1.1
  - ca-certificates=2022.5.18.1
  - cfitsio=4.1.0
  - charls=2.3.4
  - cloudpickle=2.1.0
  - colorama=0.4.4
  - cytoolz=0.11.2
  - dask-core=2022.5.0
  - debugpy=1.6.0
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - freetype=2.10.4
  - fsspec=2022.5.0
  - giflib=5.2.1
  - imagecodecs=2022.2.22
  - imageio=2.19.2
  - intel-openmp=2022.1.0
  - ipykernel=6.13.0
  - ipython=8.4.0
  - jbig=2.1
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.3.1
  - jupyter_core=4.10.0
  - jxrlib=1.1
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.6
  - libavif=0.10.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libdeflate=1.10
  - libffi=3.4.2
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.11
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib-inline=0.1.3
  - mkl=2022.0.0
  - msys2-conda-epoch=20160418
  - nest-asyncio=1.5.5
  - networkx=2.8.2
  - numpy=1.22.4
  - openjpeg=2.4.0
  - openssl=3.0.3
  - packaging=21.3
  - parso=0.8.3
  - partd=1.2.0
  - pickleshare=0.7.5
  - pillow=9.1.1
  - pip=22.1.1
  - prompt-toolkit=3.0.29
  - psutil=5.9.1
  - pthread-stubs=0.4
  - pure_eval=0.2.2
  - pygments=2.12.0
  - pyparsing=3.0.9
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pywavelets=1.3.0
  - pywin32=303
  - pyyaml=6.0
  - pyzmq=23.0.0
  - scikit-image=0.19.2
  - scipy=1.8.1
  - setuptools=62.3.2
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.38.5
  - stack_data=0.2.0
  - tbb=2021.5.0
  - tifffile=2022.5.4
  - tk=8.6.12
  - toolz=0.11.2
  - tornado=6.1
  - traitlets=5.2.1.post0
  - tzdata=2022a
  - ucrt=10.0.20348.0
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zlib=1.2.11
  - zlib-ng=2.0.6
  - zstd=1.5.2
  - pip:
    - absl-py==1.0.0
    - aniso8601==9.0.1
    - astunparse==1.6.3
    - cachetools==5.1.0
    - certifi==2022.5.18.1
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cycler==0.11.0
    - flask==2.1.2
    - flask-cors==3.0.10
    - flask-restful==0.3.9
    - flatbuffers==1.12
    - fonttools==4.33.3
    - gast==0.4.0
    - google-auth==2.6.6
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.46.3
    - h5py==3.7.0
    - idna==3.3
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.2
    - libclang==14.0.1
    - markdown==3.3.7
    - markupsafe==2.1.1
    - matplotlib==3.5.2
    - mit-semseg==1.0.0
    - oauthlib==3.2.0
    - opencv-python==4.5.5.64
    - opt-einsum==3.3.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytz==2022.1
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-gpu==2.9.1
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - tf-slim==1.1.0
    - torch==1.11.0
    - torchvision==0.12.0
    - tqdm==4.64.0
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - werkzeug==2.1.2
    - wrapt==1.14.1
    - yacs==0.1.8
